### PR TITLE
implement sum types

### PR DESCRIPTION
**Pull request by srghma**
fixes

https://github.com/purescript-codegen/purescript-ps-ast/issues/2
https://github.com/purescript-codegen/purescript-ps-ast/issues/1

### CODE REVIEW

**Comment by srghma** [comment]
will merge because I don't think it should break old code

and will rename this repo to `purescript-ps-ast-deprecated` as we conclude in the discourse chat

**Comment by srghma** [comment]
@paluh , ah, no, I cannot merge this pr myself. Could you merge it?

**Comment by paluh** [comment]
It looks like an override of the lib with _cst_. Because we have separated these two I think I should close it without merging. Am I right?

**Comment by srghma** [comment]
ou, I thought this pr is closed already

@paluh, I will close it

**Comment by paluh** [comment]
Thanks!

**Pull request closed without merging**
