### PR TITLE
feat: deprecation notice -> add

### PR DESCRIPTION
**Pull request by srghma**
@paluh

### CODE REVIEW

**Comment by srghma** [comment]
@paluh could you also rename this repo to `purescript-ps-ast-deprecated`, as we have concluded in the discourse chat

**Comment by srghma** [comment]
or `purescript-ps-ast-past`

**Comment by flip111** [comment]
Didn't see that before that "deprecated" goes into the package name. I'm not necessarily against it though.

What does the title "feat: deprecation notice -> add" mean? Do you want a change in the readme?

**Comment by paluh** [comment]
I think that we can leave it as a reference - so I prefer something like your second proposition @srghma: `purescript-ps-past`.

We can also update the README with something like:

# purescript-ps-past

If you are looking for fully fledged PS AST for your codegen solution please check the [purescript-ps-cst](https://github.com/purescript-codegen/purescript-ps-cst) library.

This project provides simple, incomplete PS AST (it covers a subset of the language) which was used for quick prototyping and codegen from typescript in the case of _purescript-react-basic-mui_ library. We keep it currently here for the reference and maybe for some further experimentation too. It is possible that we in the future we __drop it entirely__.

What do you think Guys?

**Comment by paluh** [comment]
@srghma I've renamed the repo to "past" and add the info to the README. I hope you don't mind @srghma if I just close this.

**Pull request closed without merging**
